baseURL: "https://rayspock.com/"
defaultContentLanguage: "en"
languageCode: "en-gb"
title: "Ray Yang"
theme: "hello-friend-ng"
googleAnalytics: "G-JHBWZFD03W"
enableEmoji: true
enableGitInfo: false

params:
  commit: "https://github.com/rayspock/rayspock.github.io/tree/"
  #  logo: "img/portfolio.jpg"
  mainSections: [ ]
  readingTime: true
  wordCount: true
  hotjarID: "1924229"
  socialShare: true
  comments: false
  # hello-friend-ng
  enableThemeToggle: true
  defaultTheme: "dark"
  social:
    - name: twitter
      url: 'https://twitter.com/rayspock675'
    - name: github
      url: 'https://github.com/rayspock'
    - name: linkedin
      url: 'https://www.linkedin.com/in/rayspock/'
  logo:
    logoText: ls rayspock
    logoHomeLink: /
  homeSubtitle: "🐳Software Engineer | 🚀BUIDL | 📍London"
  footer:
    trademark: 2026
    copyright: false
    author: true
    topText: [ ]
    bottomText: [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "<a href=\"https://github.com/rayspock/hugo-theme-hello-friend-ng\">Theme</a> made by <a href=\"https://github.com/rhazdon\">rhazdon</a>"
    ]
  author:
    name: "rayspock"
    website: "https://rayspock.com/"
    github: "rayspock"
    twitter: "rayspock675"
    linkedin: "rayspock"

markup:
  goldmark:
    renderer:
      unsafe: true

# Navbar
menu:
  main:
    - name: "about"
      pre: '<i class="far fa-user fa-lg"></i>'
      url: "page/about/"
      weight: 1

    - name: "work"
      pre: '<i class="far fa-user fa-lg"></i>'
      url: "page/work/"
      weight: 2

    - name: "blog"
      pre: '<i class="far fa-user fa-lg"></i>'
      url: "https://blog.rayspock.com"
      weight: 3
