name: deploy

on:
  push:
   branches:
    - hexo

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]  
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: hexo
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare source
        run: |
          cp assets/_config.yml themes/aircv/_config.yml
          cp -r assets/img/. themes/aircv/source/img/
          npm install
      - name: Run hexo generate
        run: |
          npm run build
      - name: Run hexo deploy
        env:
            GH_DEPLOY_TOKEN: ${{secrets.GH_DEPLOY_TOKEN}}
        run: |   
          git config --global user.name 'rayspock'
          git config --global user.email 'rayspock@protonmail.com'
          sed -i "s/<token>/${GH_DEPLOY_TOKEN}/g" ./_config.yml
          npm run deploy
